#!/usr/bin/python3 -u

## Copyright (C) 2014 troubadour <trobador@riseup.net>
## Copyright (C) 2014 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

import sys
import os
import time
from subprocess import call

if (os.path.exists('/var/lib/whonix/do_once/whonixsetup.done') or
   os.path.exists('/var/cache/whonix-setup-wizard/status-files/whonixsetup.done') or
   os.path.exists('/usr/share/whonix-setup-wizard/status-files/whonixsetup.skip') or
   os.path.exists('/var/cache/setup-dist/status-files/setup-dist.done') or
   os.path.exists('/usr/share/setup-dist/status-files/setup-dist.skip')
):
   print('usr/libexec/setup-wizard-dist/setup-dist_check_for_start setup-dist done file exists. Exiting.')
   sys.exit()

if os.path.exists('/run/qubes/this-is-templatevm'):
   print('usr/libexec/setup-wizard-dist/setup-dist_check_for_start /run/qubes/this-is-templatevm exists. Exiting.')
   sys.exit()

if os.path.exists('/usr/share/anon-ws-base-files/workstation'):
   if os.path.exists('/usr/share/whonix-setup-wizard/status-files/first_use_check.skip'):
      ## Qubes-Whonix only.
      ## Do not start setup-wizard-dist in Qubes-Whonix-Workstation by default.
      print('usr/libexec/setup-wizard-dist/setup-dist_check_for_start workstation detected and /usr/share/whonix-setup-wizard/status-files/first_use_check.skip exists. Exiting.')
      sys.exit()
   if os.path.exists('/usr/share/setup-dist/status-files/first_use_check.skip'):
      ## Qubes-Whonix only.
      ## Do not start setup-wizard-dist in Qubes-Whonix-Workstation by default.
      print('usr/libexec/setup-wizard-dist/setup-dist_check_for_start workstation detected and /usr/share/setup-dist/status-files/first_use_check.skip exists. Exiting.')
      sys.exit()

if os.path.exists('/usr/share/anon-gw-base-files/gateway'):
    ## Qubes-Whonix only.
    ## Display alert that 'whonix-tor-disable' service flag is set and it will need to
    ## to manually unset if user wants to be able to boot with Tor enabled.
    ## TODO: Don't depend on qubes-whonix package / 'alert' script by qubes-whonix package.
    ##       Abolish 'alert' script. Merge into systemcheck and/or anon-connection-wizard.
    ##       https://phabricator.whonix.org/T656
    if os.path.exists('/run/qubes-service/whonix-tor-disable'):
        command = '/usr/lib/qubes-whonix/alert tor-disabled /usr/lib/qubes-whonix/messages.yaml'
        call(command, shell = True)
        sys.exit()

print('usr/libexec/setup-wizard-dist/setup-dist_check_for_start executing /usr/libexec/setup-wizard-dist/setup-wizard-dist')
command = '/usr/libexec/setup-wizard-dist/setup-wizard-dist'
call(command, shell=True)
