#!/bin/bash

## Copyright (C) 2023 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x

if ! test -e /usr/bin/setup-wizard-dist ; then
  echo "/usr/bin/setup-wizard-dist does not exist!"
  exit 1
fi

if ! test -x /usr/bin/setup-wizard-dist ; then
  echo "/usr/bin/setup-wizard-dist not executeable!"
  exit 1
fi

title="$0 autostart"
status_file=~/.config/setup-wizard-dist


if ! sudo --non-interactive --set-home /usr/bin/setup-wizard-dist ; then
  text="\
command:
sudo --non-interactive --set-home /usr/bin/setup-wizard-dist
failed.

This might be due to the user using sudo hardening."

  /usr/libexec/msgcollector/one-time-popup "$status_file" "$title" "$text"
fi
