#!/bin/bash

## Copyright (C) 2023 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
shopt -s inherit_errexit
shopt -s shift_verbose

true "$0: START"

if ! test -e /usr/bin/setup-wizard-dist ; then
  printf '%s\n' "$0: ERROR: '/usr/bin/setup-wizard-dist' does not exist!"
  exit 1
fi

if ! test -x /usr/bin/setup-wizard-dist ; then
  printf '%s\n' "$0: ERROR: '/usr/bin/setup-wizard-dist' not executable!"
  exit 1
fi

/usr/bin/setup-wizard-dist

true "$0: END"
