.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "SETUP\-DIST\-WIZARD" "8" "January 2020" "setup-dist-wizard" "setup-dist-wizard Manual"
.SH "NAME"
\fBsetup\-dist\-wizard\fR \- Distribution Settings Wizard
.P
.SH "SYNOPSIS"
\fBsetup\-dist\-wizard\fR {setup,locale_settings}
.SH "DESCRIPTION"
Graphical version of \fBsetup\-dist\fR, that asks in which environment you are using, informs about various situations, helps to enable Tor in Tor config\.
.SH "EXAMPLES"
\fBsetup\-dist\-wizard setup\fR
.P
\fBsetup\-dist\-wizard locale_settings\fR
.SH "SKIP FILES"
See also \fBman setup\-dist\fR for skip files\.
.SH "WWW"
https://www\.whonix\.org
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@riseup\.net)\.
