.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "SETUP\-WIZARD\-DIST" "8" "January 2020" "setup-wizard-dist" "setup-wizard-dist Manual"
.SH "NAME"
\fBsetup\-wizard\-dist\fR \- Graphical Settings Wizard
.SH "SYNOPSIS"
\fBsetup\-wizard\-dist\fR {setup,locale_settings}
.SH "DESCRIPTION"
Graphical version of \fBsetup\-dist\fR, that asks in which environment you are using, informs about various situations, helps to enable Tor in Tor config\.
.SH "EXAMPLES"
\fBsetup\-wizard\-dist setup\fR
.P
\fBsetup\-wizard\-dist locale_settings\fR
.SH "SKIP FILES"
See also \fBman setup\-dist\fR for skip files\.
.SH "WWW"
https://www\.whonix\.org
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
